---
- name: Install HAProxy and configure for forwarding TCP traffic
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure HAProxy is installed
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Copy HAProxy config file
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

    - name: Read Haproxy config
      ansible.builtin.command:
        cmd: haproxy -c -f /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
